//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StructuralEmbodiment.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StructuralEmbodiment.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FF_BuildStructureCEM {
            get {
                object obj = ResourceManager.GetObject("FF_BuildStructureCEM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FF_BuildStructureKangaroo {
            get {
                object obj = ResourceManager.GetObject("FF_BuildStructureKangaroo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FF_CEMGenerator {
            get {
                object obj = ResourceManager.GetObject("FF_CEMGenerator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FF_InputRecorder {
            get {
                object obj = ResourceManager.GetObject("FF_InputRecorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FF_InputRecorderCSV {
            get {
                object obj = ResourceManager.GetObject("FF_InputRecorderCSV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FF_MassProducer {
            get {
                object obj = ResourceManager.GetObject("FF_MassProducer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MAT_BuildStructure {
            get {
                object obj = ResourceManager.GetObject("MAT_BuildStructure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MAT_DowntownMaker {
            get {
                object obj = ResourceManager.GetObject("MAT_DowntownMaker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MAT_ExtractMember {
            get {
                object obj = ResourceManager.GetObject("MAT_ExtractMember", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MAT_ExtractStructure {
            get {
                object obj = ResourceManager.GetObject("MAT_ExtractStructure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MAT_Materialiser {
            get {
                object obj = ResourceManager.GetObject("MAT_Materialiser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MAT_TerrainMaker {
            get {
                object obj = ResourceManager.GetObject("MAT_TerrainMaker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SE_App {
            get {
                object obj = ResourceManager.GetObject("SE_App", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[DisplayMode\66e5faf8-94cb-4762-bc92-db2907bddf33]
        ///SupportsShadeCmd=y
        ///SupportsShading=y
        ///SupportsStereo=y
        ///AddToMenu=y
        ///AllowObjectAssignment=n
        ///ShadedPipelineRequired=y
        ///WireframePipelineRequired=y
        ///PipelineLocked=y
        ///Order=15
        ///DerivedFrom=f4616fa5-a831-4620-a97e-9b807d5ec376
        ///Name=SE_Line
        ///XrayAllObjects=n
        ///IgnoreHighlights=n
        ///DisableConduits=n
        ///DisableTransparency=n
        ///BBoxMode=0
        ///RealtimeDisplayId=00000000-0000-0000-0000-000000000000
        ///PipelineId=e1eb7363-87f2-4a2b-a861-256e77835369
        ///[DisplayMode\66e5fa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SE_Line {
            get {
                return ResourceManager.GetString("SE_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[DisplayMode\181dd6f2-9e6a-4f43-8061-a76347deeb75]
        ///SupportsShadeCmd=y
        ///SupportsShading=y
        ///SupportsStereo=y
        ///AddToMenu=y
        ///AllowObjectAssignment=y
        ///ShadedPipelineRequired=y
        ///WireframePipelineRequired=y
        ///PipelineLocked=n
        ///Order=14
        ///DerivedFrom=8bc8debe-c83b-4c47-b13c-9db074510cac
        ///Name=SE_Seg
        ///XrayAllObjects=n
        ///IgnoreHighlights=n
        ///DisableConduits=n
        ///DisableTransparency=n
        ///BBoxMode=0
        ///RealtimeDisplayId=00000000-0000-0000-0000-000000000000
        ///PipelineId=952b2830-ce8a-4b4f-935a-8cd570d162c7
        ///[DisplayMode\181dd6f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SE_Seg {
            get {
                return ResourceManager.GetString("SE_Seg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SE_Tab {
            get {
                object obj = ResourceManager.GetObject("SE_Tab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VIS_BuildDepthGuide {
            get {
                object obj = ResourceManager.GetObject("VIS_BuildDepthGuide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VIS_BuildGuidance {
            get {
                object obj = ResourceManager.GetObject("VIS_BuildGuidance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VIS_BuildImageSettings {
            get {
                object obj = ResourceManager.GetObject("VIS_BuildImageSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VIS_BuildImageSettings_Legacy {
            get {
                object obj = ResourceManager.GetObject("VIS_BuildImageSettings_Legacy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VIS_BuildLineGuide {
            get {
                object obj = ResourceManager.GetObject("VIS_BuildLineGuide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VIS_BuildSegGuide {
            get {
                object obj = ResourceManager.GetObject("VIS_BuildSegGuide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VIS_RhinoVisualiser {
            get {
                object obj = ResourceManager.GetObject("VIS_RhinoVisualiser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VIS_RhinoVisualiser_Legacy {
            get {
                object obj = ResourceManager.GetObject("VIS_RhinoVisualiser_Legacy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VIS_SDVisualiser {
            get {
                object obj = ResourceManager.GetObject("VIS_SDVisualiser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VIS_SegmentationColours {
            get {
                object obj = ResourceManager.GetObject("VIS_SegmentationColours", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VIS_SetCamera {
            get {
                object obj = ResourceManager.GetObject("VIS_SetCamera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VIS_ViewRandomiser {
            get {
                object obj = ResourceManager.GetObject("VIS_ViewRandomiser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
